
hkl:
	python -m translocation --hkl test_shelx.hkl --k1 0.3 --fc1 0.3 0.1 0.2 --k2 0.1 --fc2 0.1 0.2 0.1 -o new_SHELX_file.hkl

hkl-force:
	python -m translocation --hkl test_shelx.hkl --k1 0.3 --fc1 0.3 0.1 0.2 --k2 0.1 --fc2 0.1 0.2 0.1 -o new_SHELX_file.hkl -f

HKL:
	python -m translocation --HKL test_xds.HKL --k1 0.3 --fc1 0.3 0.1 0.2 --k2 0.1 --fc2 0.1 0.2 0.1 -o new_XDS_file.HKL

sca:
	python -m translocation --sca test_dials.sca --k1 0.3 --fc1 0.3 0.1 0.2 --k2 0.1 --fc2 0.1 0.2 0.1 -o new_SCALEPACK_file.sca

test:
	python3 test.py
